'use client'

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cTocnGFSAv2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from '@/components/ui/button'
import { CardTitle, CardHeader, CardContent, Card } from '@/components/ui/card'
import { ResponsiveBar } from '@nivo/bar'
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from '@/components/ui/table'

export function Dash () {
  return (
    (<div className="flex flex-col w-full min-h-screen">
      <main
        className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="grid gap-4 md:grid-cols-3">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Total Revenue</CardTitle>
              <DollarSignIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">$45,231.89</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">+20.1% from last month</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Subscriptions</CardTitle>
              <UsersIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">+2350</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">+180.1% from last month</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Sales</CardTitle>
              <CreditCardIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">+12,234</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">+19% from last month</p>
            </CardContent>
          </Card>
        </div>
        <Card>
          <CardHeader className="flex items-center gap-2">
            <CardTitle className="text-base font-medium">Customer Satisfaction</CardTitle>
            <Button className="rounded-full" size="icon" variant="outline">
              <RefreshCwIcon className="w-4 h-4" />
              <span className="sr-only">Refresh</span>
            </Button>
          </CardHeader>
          <CardContent className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-4">
              <div className="text-4xl font-bold">4.5</div>
              <div className="flex flex-col items-start gap-1">
                <div className="flex items-center gap-1">
                  <StarIcon className="w-4 h-4 fill-accent-2" />
                  <div className="text-2xl font-semibold">1,230</div>
                </div>
                <div className="flex items-center gap-1">
                  <StarIcon className="w-4 h-4 fill-accent-2" />
                  <div className="text-2xl font-semibold">3,456</div>
                </div>
                <div className="flex items-center gap-1">
                  <StarIcon className="w-4 h-4 fill-accent-2" />
                  <div className="text-2xl font-semibold">2,345</div>
                </div>
                <div className="flex items-center gap-1">
                  <StarIcon className="w-4 h-4 fill-accent-2" />
                  <div className="text-2xl font-semibold">1,234</div>
                </div>
                <div className="flex items-center gap-1">
                  <StarIcon className="w-4 h-4 fill-accent-2" />
                  <div className="text-2xl font-semibold">5,678</div>
                </div>
              </div>
            </div>
            <div className="w-1/2">
              <BarChart className="w-full aspect-[2/1]" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex items-center gap-2">
            <CardTitle className="text-base font-medium">Top Products</CardTitle>
            <Button className="rounded-full" size="icon" variant="outline">
              <RefreshCwIcon className="w-4 h-4" />
              <span className="sr-only">Refresh</span>
            </Button>
          </CardHeader>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Product</TableHead>
                  <TableHead>Revenue</TableHead>
                  <TableHead>Orders</TableHead>
                  <TableHead className="text-right">Conversion</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="flex items-center gap-2">
                    <img
                      alt="Image"
                      className="rounded-lg"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: '40/40',
                        objectFit: 'cover'
                      }}
                      width="40" />
                    <div className="font-medium">Blue T-Shirt</div>
                  </TableCell>
                  <TableCell>$1,230.00</TableCell>
                  <TableCell>345</TableCell>
                  <TableCell className="text-right">23.5%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="flex items-center gap-2">
                    <img
                      alt="Image"
                      className="rounded-lg"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: '40/40',
                        objectFit: 'cover'
                      }}
                      width="40" />
                    <div className="font-medium">Red Shoes</div>
                  </TableCell>
                  <TableCell>$2,345.00</TableCell>
                  <TableCell>456</TableCell>
                  <TableCell className="text-right">32.1%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="flex items-center gap-2">
                    <img
                      alt="Image"
                      className="rounded-lg"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: '40/40',
                        objectFit: 'cover'
                      }}
                      width="40" />
                    <div className="font-medium">Black Hat</div>
                  </TableCell>
                  <TableCell>$1,567.00</TableCell>
                  <TableCell>234</TableCell>
                  <TableCell className="text-right">12.4%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="flex items-center gap-2">
                    <img
                      alt="Image"
                      className="rounded-lg"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: '40/40',
                        objectFit: 'cover'
                      }}
                      width="40" />
                    <div className="font-medium">White Jeans</div>
                  </TableCell>
                  <TableCell>$3,456.00</TableCell>
                  <TableCell>789</TableCell>
                  <TableCell className="text-right">45.6%</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="flex items-center gap-2">
                    <img
                      alt="Image"
                      className="rounded-lg"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: '40/40',
                        objectFit: 'cover'
                      }}
                      width="40" />
                    <div className="font-medium">Green Dress</div>
                  </TableCell>
                  <TableCell>$2,345.00</TableCell>
                  <TableCell>567</TableCell>
                  <TableCell className="text-right">34.2%</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </main>
    </div>)
  )
}

function BarChart (props) {
  return (
    (<div {...props}>
      <ResponsiveBar
        data={[
          { name: 'Jan', count: 111 },
          { name: 'Feb', count: 157 },
          { name: 'Mar', count: 129 },
          { name: 'Apr', count: 150 },
          { name: 'May', count: 119 },
          { name: 'Jun', count: 72 }
        ]}
        keys={['count']}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={['#2563eb']}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: '9999px'
            },
            container: {
              fontSize: '12px',
              textTransform: 'capitalize',
              borderRadius: '6px'
            }
          },
          grid: {
            line: {
              stroke: '#f3f4f6'
            }
          }
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data" />
    </div>)
  )
}

function CreditCardIcon (props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>)
  )
}

function DollarSignIcon (props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>)
  )
}

function RefreshCwIcon (props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>)
  )
}

function StarIcon (props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  )
}

function UsersIcon (props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  )
}
